### ISSUE TITLE
Add Usage Hint to the README.md

### ISSUE THREAD

**Issue by ixidion** [awslabs/aws-cfn-lint-atom#10]
A more clear note should be added to the README.md, that the errors and warning from lint are only shown, if the file starts with the parameter, e.g. a usage snippet from one of the template files.
`AWSTemplateFormatVersion: "2010-09-09"`

The [bad.yml](https://github.com/awslabs/aws-cfn-lint-atom/blob/master/spec/fixtures/templates/bad.yaml) brought me on the right track.

**Comment by fatbasstard** [comment]
You mean the explicit paragraph in the readme explaining this?

**Comment by fatbasstard** [comment]
Fix me this is perfectly clear. But that's me of course. Can you make a PR improve the documentation on this part?
