### ISSUE TITLE
Documentation about the working in Atom

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/aws-cfn-lint-atom#2]
I've just installed the plugin in Atom.... But how does it work, how do I enable it?

**Comment by fatbasstard** [comment]
Got it up and running 👍 

I'll make a PR to improve documentation and/or improve code

**Comment by kddejong** [comment]
I'm really curious @fatbasstard what you had to do to get this working.  I hope it was as easy as just configuring the path to cfn-lint.

**Comment by cmmeyer** [comment]
For me, it was un-obvious that the presence of the version line in a JSON or YAML file was enough to activate the linter. :)

**Comment by kddejong** [comment]
Yes.  That is a good one.  Resources is technically the only required element.  We could change it to that but we could trigger other types of templates by accident.  Thoughts?

**Comment by xdrus** [comment]
My steps to make it working:
* install steelbrain/linter in atom with dependencies
* install awslabs/atom-cfn-lint
* install cfn-lint
```
pip install cfn-lint
```
* Configure "cfn-lint" path in "atom-cfn-lint" settings
* Ensure that templates have "AWSTemplateFormatVersion"

**Comment by fvanboven** [comment]
For me it was the installation of some requirements that are not dependencies (so they are not automatically installed), indeed the steelbrain/linter (Can we make that a real depency so it's auto installed?

Apart from that I did nothing, even the default path was fine. I'll see if I can fix this ASAP

**Comment by fvanboven** [comment]
> Yes. That is a good one. Resources is technically the only required element. We could change it to that but we could trigger other types of templates by accident. Thoughts?

Although Resources indeed is the only mandatory part (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html) it feels "weird", `Resources` is a pretty generic name that is not AWS/Cfn specific. And since `AWSTemplateFormatVersion ` is a best practice I like it the way it is. That a clear "This is an AWS CloudFormation template definition

**Comment by kddejong** [comment]
> And since AWSTemplateFormatVersion is a best practice I like it the way it is. That a clear "This is an AWS CloudFormation template definition

This is my opinion as well.   

> indeed the steelbrain/linter (Can we make that a real depency so it's auto installed?

I'll check this out.  I'm sure we can make this a dependency.

**Comment by fatbasstard** [comment]
I'm also looking at it ATM, should be fairly easy

**Comment by kddejong** [comment]
@fatbasstard I may have beaten you to it.  Let me know if this pull request is doing what you are thinking.

**Comment by fatbasstard** [comment]
Yes. `1 commit ahead, 1 commit behind`. Beat me by 10 minutes...

I had the same change basically 👍 the `package-deps` should do the trick.

**Comment by cmmeyer** [comment]
Ha! Everyone kick the tires and let me know if we're good to close.  I may go install a Workspace just to get that clean environment experience.

**Comment by fatbasstard** [comment]
Just installed the new version (`0.4.1`) on my colleague's system. Dependency installation works like a charm 💯 

He got one minor notification about linters ("You have both `linter` and `atom-ide-diagnostics` enabled, which will both display lint results for Linter-based-packeges"). First Google result gave https://discuss.atom.io/t/atom-ide-and-linter-package-together/48841

Since this is the way packages and dependencies work, I don't consider this an issue.

So I'd say: Close it 👍

**Comment by kddejong** [comment]
Thanks @fatbasstard
