### ISSUE TITLE
validation error with cloudwatch alarm syntax

### ISSUE THREAD

**Issue by sarangrao** [awslabs/aws-cfn-lint-atom#21]
Hi,
I have a cloudformation that has a cloudwatch alarm as below:

EC2RootDiskUsedWarningAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: True
      AlarmActions: [ !Ref AppAlertTopic ]
      AlarmName: !Sub alarm-${AWS::Region}-${AppName}-${Env}-${Component}-${ServerNum}-EC2-RootLowDiskSpace-Warning
      ComparisonOperator: LessThanOrEqualToThreshold

I get a validation error with this
You must specify a valid value for ComparisonOperator (LessThanOrEqualToThreshold). Valid values are ['GreaterThanOrEqualToThreshold', 'GreaterThanThreshold', 'LessThanOrEqualToThreshold.', 'LessThanThreshold']

It appears that there is a typo in the check for the value of "LessThanOrEqualToThreshold". It is looking for a value "LessThanOrEqualToThreshold." with a period at the end.

**Comment by kddejong** [comment]
Update your cfn-lint to v0.13.2 should be fixed then.

https://github.com/awslabs/cfn-python-lint/issues/628
