### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Ipswitch** [awslabs/aws-cfn-lint-atom#24]
An unexpected error with cloudformation, cfn-lint, atom-cfn-lint, atom, linter, and/or your playbook, has occurred.

spawn cfn-lint ENOENT

**Comment by kddejong** [comment]
By default atom will look for `cfn-lint` in your paths if it can't be found you will see this error.

Under settings of the package you can configure the path to `cfn-lint` and this issue will go away.  Remember you also have to install [`cfn-lint`](https://github.com/awslabs/cfn-python-lint)

**Comment by aaronfranco** [comment]
I'm getting the same error but mine states: 
error: unknown option `--format' 

at the end
