### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by pjgsmit** [awslabs/aws-cfn-lint-atom#25]
AWS::Backup::BackupVault
Invalid or unsupported Type AWS::Backup::BackupVault for resource.

**Comment by pjgsmit** [comment]
AWS::Backup::BackupVault
Invalid or unsupported Type AWS::Backup::BackupVault for resource.

**Comment by PatMyron** [comment]
Using the latest [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) by running this on the command line should solve this:
`cfn-lint -u`
