### ISSUE TITLE
Better support for Null Values?

### ISSUE THREAD

**Issue by xdrus** [awslabs/aws-cfn-lint-atom#3]
## Issue description
if cfn-lint throws error "Template... contains nulls: Null value at line XX column YY" plugin just shows error (see screenshot)

## Intended behavior
Since error message has information regarding error source it would be great pointing to line XX column YY instead.

## Sample snippet
```
  SomeResource:
    Type:
```

## cfn-lint output
```
$ cfn-lint --template ecs-optimized.yaml 
2018-05-17 19:22:38,870 - cfnlint - ERROR - Template ecs-optimized.yaml contains nulls: Null value at line 22 column 19
```

## atom-cfn-int-atom output
https://www.dropbox.com/s/6k83c32huufw4cj/Screen%20Shot%202018-05-17%20at%207.20.55%20PM.png?dl=0

**Comment by kddejong** [comment]
Released with cfn-lint 0.2.0.  Please upgrade and let us know if you still have issues.
