### ISSUE TITLE
EC2 Image Builder Types not recognized

### ISSUE THREAD

**Issue by TheMrJS** [awslabs/aws-cfn-lint-atom#30]
atom-cfn-lint version 0.7.0
atom version 1.52.0

Linter does not recognize any of the CloudFormation types related to EC2 Image Builder, which makes writing these templates extremely tedious. I have deployed my Cloudformation templates into AWS successfully, so they are confirmed to be working.

**Comment by PatMyron** [comment]
`cfn-lint` itself needs to be upgraded for new CloudFormation type support:
[`pip3 install cfn-lint --upgrade`](https://github.com/aws-cloudformation/cfn-python-lint/#install)
