### ISSUE TITLE
Add linter to http://atomlinter.github.io/

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/aws-cfn-lint-atom#6]
Now that the dependency on the linter is clear and locked (https://github.com/awslabs/aws-cfn-lint-atom/issues/2) 

Fairly easy to "register" this linter @ http://atomlinter.github.io/, shall we do that?

**Comment by cmmeyer** [comment]
+1 to this.  Be nice to see CloudFormation in the list! 
@kddejong -- i can jump through the hoops if you're cool with it.

**Comment by kddejong** [comment]
https://github.com/AtomLinter/atomlinter.github.io/pull/84

**Comment by fatbasstard** [comment]
That was quick.... 👍 

I'll close the issue then
