### ISSUE TITLE
Intelligent conditionals

### ISSUE THREAD

**Issue by navneetpare** [awslabs/aws-cfn-lint-atom#8]
Hello folks, 

Firstly, thanks for this awesome plugin! This isn't exactly a bug, but was wondering if it would help.

I was testing the attached template and the linter (correctly) caught an issue where if an RDS DBSnapshotIdentifier is added, the 'MasterUsername' and 'MasterUserPassword' attributes are flagged as invalid. I've used a conditional to do AWS::NoValue if the identifier IS provided. Would it make sense to flag this as a warning instead of an error? (I suppose this could be extended to conditional parameters in general?)

Thanks

![snapshot](https://user-images.githubusercontent.com/22359439/41139014-ae368b74-6b02-11e8-94ec-e2d64d9e8fb7.PNG)
[RDSFromSnapshot.txt](https://github.com/awslabs/aws-cfn-lint-atom/files/2082931/RDSFromSnapshot.txt)

**Comment by kddejong** [comment]
Thanks for the feedback.  Yea conditions can be tricky.  We are discussing some better options around those right now.  What we have to tried to do is to 'pass' when the situation is complicated beyond our ability to compute it.   I may put in a quick fix for that but we also have the understanding we need a better solution to handle conditions.

Do you know as the template is will it work?  Does DBSnapshotIdentifier have to be in a Condition too?

**Comment by navneetpare** [comment]
Yup, the template works fine. Attached a simplified version just for the DB. 

The flagged parameters are 'NoValue'd if the snapshot id isn't provided.
[RDS_Conditionals.txt](https://github.com/awslabs/aws-cfn-lint-atom/files/2086623/RDS_Conditionals.txt)

**Comment by kddejong** [comment]
We removed this from the check until we can write more logic around conditions for RDS.  The empty value item is tricky and we will circle back on it.  v0.4.2 of cfn-lint
